project_id = "sabsewa-local"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "sabsewalocal://auth"
additional_redirect_urls = ["sabsewalocal://auth"]
jwt_expiry = 3600
enable_signup = true

[storage]
enabled = true

[edge_runtime]
enabled = true

[functions.razorpay-create-platform-order]
verify_jwt = false

[functions.razorpay-verify-platform-payment]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.razorpay-create-platform-refund]
verify_jwt = false
